### ISSUE TITLE
Loading blob URL from Audio.fromFile

### ISSUE THREAD

**Issue by ChunAllen** [SEERNET/deepaffects-node#7]
I'm currently using deep affects emotion analyser for reading audio
Is it possible to load from blob?
For example:
```
DeepAffects.Audio.fromFile("blob:url_here");
```

**Comment by viveknimkarde** [comment]
Hi Allen,
Thanks for reaching out.

Currently `DeepAffects.Audio.fromFile("LOCAL_FILE_PATH");` function expects a valid audio path on the file system, so blob url might not work here. 

For your use case You can do few things as follows:
- Download blob as file and the pass it to `DeepAffects.Audio.fromFile("LOCAL_FILE_PATH");`
- Convert blob to base64 and and pass it as content parameter in the request body, thats what `.fromFIle` does under the hood.

Thanks
DeepAffects

**Comment by ChunAllen** [comment]
Hi @viveknimkarde  I'll use the conversion of blob to base64 because I'm planning to deploy the application to Heroku which don't have a file storage folder.
So currently the blob I'm getting is this: 
```
var url = URL.createObjectURL(AudioBLOB);
console.log(url);
```
the snippet above returns 
`blob:http://localhost:3001/fcd3f823-5254-4909-9702-e58ded38ce09`

so you mean if I convert the result above to base64 so I should be able to pass it in the `.fromFile` function?

**Comment by viveknimkarde** [comment]
@ChunAllen Browser can directly give you base64 converted audio as follows 
``` 
var reader = new FileReader();
 reader.readAsDataURL(blob); 
 reader.onloadend = function() {
     base64data = reader.result;                
     console.log(base64data);
 }
```

just use it as content parameter for request body.
no need to use .fromFile in the browser
