### ISSUE TITLE
Inaccurate result of analyzing emotion

### ISSUE THREAD

**Issue by ChunAllen** [SEERNET/deepaffects-node#8]
I checked your website https://www.deepaffects.com/emotion-recognition-api/ and in the first section where you can play the sounds by emotion, I grab the sound file of `happy` which is this url
[Happy Audio](http://static1.squarespace.com/static/58e3ecc75016e194dd5125b0/t/58e919fcc534a5cb833f1bf3/1491671548810/YAF_boat_happy.mp3/original/YAF_boat_happy.mp3)

I converted the audio file to `wav` format and load the file using your api

```
  var body = DeepAffects.Audio.fromFile("happy-audio.wav");

  var callback = function(error, data, response) {
    if (error) {
      console.error(error);
    } else {
      console.log('API called successfully. Returned data: ' + data.length);
      for(var i=0; i < data.length; i++) {
        console.log("Emotion: " + data[i].emotion + " Score: " + data[i].score);
      }
    }
  };

  var result = apiInstance.syncRecogniseEmotion(body, callback);
  res.json(result);

```

The result I am getting is
<img width="337" alt="screenshot 2018-07-26 11 29 23" src="https://user-images.githubusercontent.com/2100728/43240013-31945a2a-90c7-11e8-9763-e4c2babddf51.png">
the highest score mood is **neutral** but the audio file that I used is **happy**

**Comment by sushant-hiray** [comment]
Please check the scores carefully. The neutral score is 4.9e-24 which is effectively 0. Happy is the highest score. 

Also, only open issues related to the `deepaffects-node` in this repository. For any other support issues, raise request here: https://deepaffects.atlassian.net/servicedesk/customer/portal/1
